// Generated by https://quicktype.io

import { Product } from "../products/ProductsResponse";

export interface FullCategory {
    id:          string;
    name:        string;
    slug:        string;
    description: string;
    image:       string;
    createdAt:   string;
    updatedAt:   string;
    products:    Product[];
}